# Generated by Django 5.0.6 on 2024-06-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('ai', 'AI Development'), ('game', 'Game Development'), ('miscellaneous', 'miscellaneous')], default='Web Development', max_length=15),
            preserve_default=False,
        ),
    ]
