# Generated by Django 5.0.6 on 2024-09-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliov3', '0002_projects_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='long_description',
            new_name='link',
        ),
    ]
